# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 40146a18e836369ebeed181233afc1ea1aa198dcafe99bdd63b8e2a548847032fbba3dad000b3a30aaff8f84cd4f132a32b10b6727cdfe065b0678ddfc57816a

test:
  secret_key_base: e9a2d0d54ffb5aa79c9cf349da06be827e4809ea165dd3bcc9c25d3ed64b991c8d35109687e4124153e078a1dd412a8c3a4b7ede0cc6271a53aa5e9f8730c217

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
